### ISSUE TITLE
Check docker credentials and package dependencies at the beginning of the basic_checks.yaml Action

### ISSUE THREAD

**Issue by cmirzayi** [seandavi/BuildABiocWorkshop#10]
Hi,

I had some issues getting the action to run without error--nothing too serious but I did have to wait 13 minutes to find out that I had entered the wrong docker username/password (visible here: https://github.com/cmirzayi/EpiForBioWorkshop2020/runs/774158738?check_suite_focus=true) and 19 minutes before failure because I had not added pkgdown as a dependency (https://github.com/cmirzayi/EpiForBioWorkshop2020/runs/774201957?check_suite_focus=true). If possible, it would be good if the action checked for these sorts of errors before running for 10+ minutes.

Thanks!
Chloe

**Comment by seandavi** [comment]
Thanks, @cmirzayi. These are great suggestions! If you end up implementing them for your own repo, drop your solution here and perhaps on slack to let others know what you did. As an aside your workshop is looking fantastic!

**Comment by seandavi** [comment]
We've switched from using dockerhub to github container registry, so this issue no longer applies.
