### ISSUE TITLE
How to format DOCKER_USERNAME in secrets?

### ISSUE THREAD

**Issue by jdrnevich** [seandavi/BuildABiocWorkshop#22]
I have an issue that is slightly related to #10 . I too had issues with my docker credentials failing after 10+ minutes of the action (although in my case I am glad it failed after making the pkgdown website, not before). I think my problem is that I am not formatting the DOCKER_USERNAME and DOCKER_PASSWORD properly and I cannot find an example anywhere. My action fails with 
```
Pushing image [jdrnevich/buildacarpentriesworkshop:latest jdrnevich/buildacarpentriesworkshop:latest jdrnevich/buildacarpentriesworkshop:sha-38bb549]
The push refers to repository [docker.io/jdrnevich/buildacarpentriesworkshop]
60176156405e: Preparing
... # removed a bunch of Preparing and Waiting lines
30691b678e1c: Waiting
denied: requested access to the resource is denied
Error: exit status 1
Usage:
  github-actions build-push [flags]
```

I created a docker account and got an access token. How exactly should I enter them in the secrets? I have tried:

```
DOCKER_USERNAME: jdrnevich
DOCKER_PASSWORD: mytokenid
```
and
```
DOCKER_USERNAME jdrnevich
DOCKER_PASSWORD mytokenid
```
Both failed. Instead of trying lots of combos and waiting 10 min to see, I thought I'd ask here and also request you add the formatting to Section 6 of HOWTO_BUILD_WORKSHOP.Rmd. Thanks!

**Comment by seandavi** [comment]
Apologies, @jdrnevich, for not getting to this sooner. We've ditched using DockerHub as the docker repository and instead are using the GitHub Container Registry. This alleviates the need for supplying docker secrets. Your docker will end up at ghcr.io/GITHUB_USERNAME/REPO_NAME.
