### ISSUE TITLE
Deployment workflow out of date

### ISSUE THREAD

**Issue by ahl27** [seandavi/BuildABiocWorkshop#31]
Hi there,

Following the instructions in the package exactly leads to failing GH Action checks at the "Deploy" phase of `r-build-and-check`. This is presumably due to an error introduced within the past month causing the workflow to be unable to initialize a repository (see [Issue #1110](https://github.com/JamesIves/github-pages-deploy-action/issues/1110), [Issue #1083](https://github.com/JamesIves/github-pages-deploy-action/issues/1083)). This has subsequently been fixed in later releases, but the workflow bundled in the template repository doesn't seem to work.

The fixes for this are:
- update `JamesIves/github-pages-deploy-action@releases/v3 -> JamesIves/github-pages-deploy-action@releases/v4` in `basic_checks.yaml:68`
- Add an entry in the README to tell users to ensure "Read and Write permissions" are checked under Settings > Actions > General > Workflow permissions

**Comment by seandavi** [comment]
Thanks for doing my homework for me!
