### ISSUE TITLE
An error from `sysreqs` is causing the GitHub Actions workflow in this template to fail

### ISSUE THREAD

**Issue by ChristopherEeles** [seandavi/BuildABiocWorkshop#33]
Hello @seandavi and team,

I already opened an issue on the `sysreqs` repo about this, see: https://github.com/r-hub/sysreqs/issues/24. Starting last night, the GHA workflow to build my workshop started failing even though I had only incremented the package version number.

Wondering if this is happening to anyone else? I am pretty sure it is due to an expired SSL certification for the sysreq website, see the issue for more details.

Best,
Christopher Eeles
Software Developer
Haibe-Kains Lab
PM-Research | UHN

**Comment by seandavi** [comment]
I think this has been resolved. Reopen if not... And thanks for letting the sysreqs folks know.
